config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #
  # Upload Area
  #

  post 'image' => 'upload#upload_image'
  post 'image_base64' => 'upload#upload_base64_image'
  post 'upload_avatar' => 'upload#upload_avatar'

  #
  # Blog Area
  #
  resources :posts, path: :blog, except: [:index] do
    resources :comments, only: [:create]
  end
  resources :tags, only: [:index, :show]
  resources :columns, only: [:index, :show]

  #
  # Search
  #

  get 'search' => 'search#search'

  #
  # Admin Area
  #
  namespace :admin do
    root to: "dashboard#index"
    resources :posts
    resources :comments, only: [:index, :create, :update, :destroy]
    resources :columns, except: [:update] do
      collection do
        put :update_column
      end
    end
    resources :tags, except: [:update] do
      collection do
        put :update_tag
      end
    end
    resources :pages
    resource :settings, only: [:show, :create]
  end

  #
  # User Area
  #
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root to: 'posts#index'

  #
  # Page Area
  #
  resources :pages, only: [:show], path: "/" do
    resources :comments, only: [:create]
  end

end

app/views/admin/pages/_edit.html.haml
%ol.breadcrumb
  %li
    %i.fa.fa-dashboard.fa-prl5
    = link_to admin_root_path do
      管理首页
  %li
    %i.fa.fa-list-alt.fa-prl5
    = link_to admin_pages_path do
      页面管理
  %li.active
    %i.fa.fa-pencil.fa-prl5
    修改页面
.new-article
  = render 'form'

app/views/admin/pages/_form.html.haml
= javascript_include_tag 'mdeditor'
= form_for [:admin, @page], html: {onsubmit: "html_content();"} do |f|
  - if @page.errors.any?
    #error_explanation.alert.alert-danger.alert-dismissible.fade.in
      = button_tag class: 'close', 'data-dismiss' => 'alert', 'aria-label' => 'Close' do
        %span{ 'aria-hidden' => 'true' }
          x
      %h4= "#{@page.errors.count} 个错误导致保存失败："
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title, '页面标题'
    = f.text_field :title, class: 'form-control', autofocus: true, required: true
  .form-group
    = f.label :path, '页面路径'
    .input-group
      %span.input-group-addon
        https://#{Settings.blogine.host}/
      = f.text_field :path, class: 'form-control', required: true
  .form-group
    = f.label :content, '页面内容'
    -# a bug around haml whitespace, I have find some solutions: https://github.com/haml/haml/issues/643#issuecomment-255546050
    = f.text_area :content, class: 'form-control'
    = f.hidden_field :html_content
    = f.hidden_field :status
  .fixed-area
    .content#pages_content
      = button_tag '存为草稿', id: :submit_draft, class: 'btn btn-default btn-sm'
      = button_tag '提交', id: :submit_form, class: 'btn btn-primary btn-sm'
= javascript_include_tag 'admin/bootstrap-tagsinput.min'
= javascript_include_tag 'admin/bootstrap3-typeahead.min'

:javascript
  window.onbeforeunload = function() {
    return '';
  }
  $("#page_content").markdown({
    language: 'zh',
    imgurl: '/image',
    base64url: '/image_base64',
    fullscreen: {
        enable: true
    },
    autofocus: false,
    resize: 'vertical',
    hiddenButtons: ['cmdEmoji'],
    iconlibrary: 'fa'
  });
  $(document).ready(function() {
    $("form input[name*='page']").bind("keypress", function(e) {
      if (e.keyCode == 13) {
          return false;
      }
    });
  });
  function html_content(){
    $('#page_html_content').val(marked($('#page_content').val()))
  }
  $('#submit_form').click(function(){
    $('#post_tags').val($('#tags').val())
    window.onbeforeunload = null
    $('form').submit()
  })
  $('#submit_draft').click(function(){
    $('#post_tags').val($('#tags').val())
    $('#post_status').val(1)
    window.onbeforeunload = null
    $('form').submit()
  })

app/views/admin/pages/_index.html.haml
%ol.breadcrumb
  %li
    %i.fa.fa-dashboard.fa-prl5
    = link_to admin_root_path do
      管理首页
  %li.active
    %i.fa.fa-list-alt.fa-prl5
    页面管理
#admin-page-index
  .table-responsive
    %table.table.table-bordered.table-hover.table-striped
      %thead
        %tr
          %th 页面Title
          %th 路径
          %th 评论数
          %th 创建时间
          %th 状态
          %th 操作
      %tbody
        - @pages.each do |p|
          %tr{class: "page-#{p.id}"}
            %td
              = link_to p.title, edit_admin_page_path(p)
            %td
              = p.path
            %td
              = p.comments_count
            %td
              = p.created_at.localtime.strftime("%x %H:%M")
            %td
              已发布
            %td
              = link_to edit_admin_page_path(p), class: 'has-tooltip operation-fa-pr3', 'data-original-title' => '编辑文章', 'data-placement' => 'top', 'data-toggle' => 'tooltip' do
                .fa.fa-pencil-square
              = link_to admin_page_path(p), method: :delete, class: 'has-tooltip operation-fa-pr3', 'data-original-title' => '删除文章', 'data-placement' => 'top', 'data-toggle' => 'tooltip', 'data-confirm' => '删除文章不可恢复，确定要删除？', remote: true do
                .fa.fa-trash
              = link_to p, class: 'has-tooltip operation-fa-pr3', 'data-original-title' => '查看页面', 'data-placement' => 'top', 'data-toggle' => 'tooltip', target: '_blank' do
                .fa.fa-eye
        %tr.add-tags-btn
          %td.td-button{colspan: 6}
            = link_to new_admin_page_path do
              .fa.fa-plus.fa-pr5.table-bottom-btn
                添加页面
= paginate @pages

app/views/admin/pages/_new.html.haml
%ol.breadcrumb
  %li
    %i.fa.fa-dashboard.fa-prl5
    = link_to admin_root_path do
      管理首页
  %li
    %i.fa.fa-list-alt.fa-prl5
    = link_to admin_posts_path do
      页面管理
  %li.active
    %i.fa.fa-pencil.fa-prl5
    创建页面
.new-article
  = render 'form'

app/views/admin/pages/destroy.js.haml
:plain
  $(".page-#{@page.id}").remove();
  notifyTop("删除成功！");

app/views/admin/pages/edit.html.haml
- title '修改页面'
= render 'edit'

app/views/admin/pages/edit.js.haml
:plain
  $("#page-wrapper").html("#{escape_javascript(render('edit'))}");
  $('.side-nav .active').removeClass('active')
  $('.side-nav .admin-page').addClass('active')

app/views/admin/pages/index.html.haml
- title '页面管理'
= render 'index'

app/views/admin/pages/index.js.haml
:plain
  $("#page-wrapper").html("#{escape_javascript(render('index'))}");
  $('.side-nav .active').removeClass('active')
  $('.side-nav .admin-page').addClass('active')

app/views/admin/pages/new.html.haml
- title '新建页面'
= render 'new'

app/views/admin/pages/new.js.haml
:plain
  $("#page-wrapper").html("#{escape_javascript(render('new'))}");
  $('.side-nav .active').removeClass('active')
  $('.side-nav .admin-page').addClass('active')