config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #
  # Upload Area
  #

  post 'image' => 'upload#upload_image'
  post 'image_base64' => 'upload#upload_base64_image'
  post 'upload_avatar' => 'upload#upload_avatar'

  #
  # Blog Area
  #
  resources :posts, path: :blog, except: [:index] do
    resources :comments, only: [:create]
  end
  resources :tags, only: [:index, :show]
  resources :columns, only: [:index, :show]

  #
  # Search
  #

  get 'search' => 'search#search'

  #
  # Admin Area
  #
  namespace :admin do
    root to: "dashboard#index"
    resources :posts
    resources :comments, only: [:index, :create, :update, :destroy]
    resources :columns, except: [:update] do
      collection do
        put :update_column
      end
    end
    resources :tags, except: [:update] do
      collection do
        put :update_tag
      end
    end
    resources :pages
    resource :settings, only: [:show, :create]
  end

  #
  # User Area
  #
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root to: 'posts#index'

  #
  # Page Area
  #
  resources :pages, only: [:show], path: "/" do
    resources :comments, only: [:create]
  end

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  content          :text(65535)
#  html_content     :text(65535)
#  creator_name     :string(255)
#  creator_email    :string(255)
#  creator_site     :string(255)
#  commentable_id   :integer
#  status           :integer          default(0)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  commentable_type :string(255)
#  parent_id        :integer          default(0)
#

class Comment < ApplicationRecord
  belongs_to :commentable, counter_cache: true, polymorphic: true
  has_many :children, foreign_key: 'parent_id', class_name: 'Comment'
  paginates_per 20

  AUTHOR_COMMENT = 2
  VERIFIED = 1
  UNVERIFIED = 0

  # get all top comments with .unconcealed, get comments group with .unconcealed.includes(:children)
  scope :unconcealed, -> {where(status: [VERIFIED, AUTHOR_COMMENT], parent_id: 0)}

  def verified?
    status == 1
  end

  def saved?
    id && persisted?
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  def index
    @comments = Comment.all.order('created_at DESC').page(params[:page])
  end

  # reply comment for admin
  def create

  end

  # check comment valid or not
  def update
    @comment = Comment.find_by_id(params[:id])
    @comment.update_column(:status, params[:status])
    respond_to do |format|
      format.js
    end
  end

  # delete comment
  def destroy
    @comment = Comment.find_by_id(params[:id]).destroy
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    if Settings.blogine.enable_captcha && !verify_rucaptcha?(nil, keep_session: true)
      return @wrong_captcha = true
    end
    if params[:post_id].present?
      @target = Post.find_by_ident(params[:post_id])
    elsif params[:page_id].present?
      @target = Page.find_by_path(params[:page_id])
    end
    @comment = @target.comments.new(comment_params)
    @comment.status = 2 if current_user

    respond_to do |format|
      @comment.save
      format.js
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :html_content, :creator_name, :creator_email, :creator_site, :parent_id)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper

  def author_class(status)
    status == 2 ? 'by-author' : ''
  end

  def comment_avatar(status, email)
    if status == 2
      Settings.blogine.avatar
    else
      gravatar_image(email)
    end
  end
end

app/views/admin/comments/_index.html.haml
%ol.breadcrumb
  %li
    %i.fa.fa-dashboard.fa-prl5
    = link_to admin_root_path do
      管理首页
  %li.active
    %i.fa.fa-comments.fa-prl5
    评论管理
#admin-comment-index
  .table-responsive
    %table.table.table-bordered.table-hover.table-striped
      %thead
        %tr
          %th ID
          %th 内容
          %th 昵称
          %th 邮箱
          %th 评论于
          %th 创建时间
          %th 状态
          %th 操作
      %tbody
        - @comments.each do |c|
          %tr{id: "comment-#{c.id}"}
            %td
              = c.id
            %td
              = c.content
            %td
              = c.creator_name
            %td
              = c.creator_email
            %td
              = link_to "#{c.commentable_type == 'Post'? post_path(c.commentable) : page_path(c.commentable)}#comments" , target: '_blank' do
                = c.commentable.title
            %td
              = c.created_at.localtime.strftime("%x %H:%M")
            %td.status
              - if c.verified?
                已通过
              - else
                未通过
            %td.operation
              .verfy-button
                - if c.status == 2
                  .label.label-default.label-mr5
                    自己
                - elsif c.verified?
                  = link_to admin_comment_path(c, {status: 0}), method: :put, remote: true do
                    .label.label-default.label-mr5
                      撤回
                - else
                  = link_to admin_comment_path(c, {status: 1}), method: :put, remote: true do
                    .label.label-success.label-mr5
                      通过
              -#.label.label-warning.label-mr5
              -#  回复
              = link_to admin_comment_path(c), method: :delete, remote: true, data: {confirm: '确认删除此评论?'} do
                .label.label-danger.label-mr5
                  删除
= paginate @comments

app/views/admin/comments/destroy.js.haml
:plain
  comment = $('#comment-#{@comment.id}');
  comment.remove();
  notifyTop("删除成功！");

app/views/admin/comments/index.html.haml
- title '评论管理'
= render 'index'

app/views/admin/comments/index.js.haml
:plain
  $("#page-wrapper").html("#{escape_javascript(render('index'))}");
  $('.side-nav .active').removeClass('active')
  $('.side-nav .admin-comment').addClass('active')

app/views/admin/comments/update.js.haml
:plain
  comment = $('#comment-#{@comment.id}')
  comment.find('.status').text('#{@comment.verified? ? '已通过':'未通过'}')
  html = "<a data-remote='true' rel='nofollow' data-method='put' href='/admin/comments/#{@comment.id}?status=#{@comment.verified? ? '0':'1'}'><div class='label label-#{@comment.verified? ? 'default':'success'} label-mr5'>#{@comment.verified? ? '撤回':'通过'}</div></a>"
  comment.find('.verfy-button').html(html)
  notifyTop("处理成功！");