config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #
  # Upload Area
  #

  post 'image' => 'upload#upload_image'
  post 'image_base64' => 'upload#upload_base64_image'
  post 'upload_avatar' => 'upload#upload_avatar'

  #
  # Blog Area
  #
  resources :posts, path: :blog, except: [:index] do
    resources :comments, only: [:create]
  end
  resources :tags, only: [:index, :show]
  resources :columns, only: [:index, :show]

  #
  # Search
  #

  get 'search' => 'search#search'

  #
  # Admin Area
  #
  namespace :admin do
    root to: "dashboard#index"
    resources :posts
    resources :comments, only: [:index, :create, :update, :destroy]
    resources :columns, except: [:update] do
      collection do
        put :update_column
      end
    end
    resources :tags, except: [:update] do
      collection do
        put :update_tag
      end
    end
    resources :pages
    resource :settings, only: [:show, :create]
  end

  #
  # User Area
  #
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root to: 'posts#index'

  #
  # Page Area
  #
  resources :pages, only: [:show], path: "/" do
    resources :comments, only: [:create]
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  before_action :enable_search, only: [:search]

  def search
    # TODO: add paginate
    return if params[:query].blank?
    @search = Post.search do
      fulltext params[:query] do
        highlight :title, :content
      end
      with(:status, 0) if current_user.blank?
    end
  end

  private

  def enable_search
    return redirect_to root_path, alert: '搜索功能未开启，请按手册配置好环境并开启搜索功能。' unless Settings.blogine.enable_search
  end

end

app/helpers/search_helper.rb
module SearchHelper

  def highlight_result(hit, result, key)
    return result.title if hit.highlights(key).blank? && key == :title
    return result.intro if hit.highlights(key).blank? && key == :content
    result = ''
    hit.highlights(key).each_with_index do |h, index|
      result << h.format { |word| "<div class='keywords'>#{word}</div>" }
      result << '...' if index > 1
    end
    result
  end

end

app/views/search/search.html.haml
.search-box
  = form_tag search_path, method: :get, class: 'search-form' do
    .input-group
      = text_field_tag :query, params[:query], placeholder: '请输入关键词搜索文章', class: 'form-control', autofocus: true
      %span.input-group-btn
        = button_tag '搜索', class: 'btn btn-primary'

  - if @search && @search.total != 0
    .result-count
      搜出相关结果
      = @search.total
      条
    .blog-list
      - @search.each_hit_with_result do |hit, post|
        .post-item
          .post-title
            = link_to post, target: '_blank' do
              = raw highlight_result(hit, post, :title)
          .post-intro
            = raw highlight_result(hit, post, :content)
          .post-detail
            .detail-item
              .fa.fa-clock-o.fa-pr5
              = post.created_at.localtime.to_formatted_s(:long)
            .detail-item
              = link_to "#{post_path(post)}#comments" , target: '_blank' do
                .fa.fa-comments-o.fa-pr5
                = post.comments_count
            .detail-item
              - if post.column.present?
                = link_to post.column, target: '_blank' do
                  .fa.fa-columns.fa-pr5
                  = post.column.name
            .detail-item
              - if post.tags.present?
                .fa.fa-tags.fa-pr5
                - post.tags.each do |t|
                  = link_to t, target: '_blank' do
                    .label.label-default.label-mr5{class: highlight_class(t.name == @tag.try(:name) ? t.name : nil)}
                      = t.name
  - else
    %p.no-results
      = params[:query].present? ? "暂无 #{params[:query]} 相关的搜索结果" : '这里什么都没有呢，搜一下看看～～～'